name = "leanses"
testDriver = "LeansesTest"
defaultTargets = ["Leanses"]

[leanOptions]
autoImplicit = false

[[lean_lib]]
name = "Leanses"

[[lean_lib]]
name = "LeansesTest"
globs = ["LeansesTest.+"]
